#!/usr/bin/env python3

from json import dump, dumps, loads
from sys import stdin, argv
from os import path

if len(argv) != 2:
    print(f"Unexpected number of parameters passed, expected exactly 1 but got {len(argv) - 1}")
    exit(1)

concourse_input = loads(stdin.read())

assert isinstance(concourse_input, dict)
assert isinstance(concourse_input["version"], dict)
assert isinstance(concourse_input["version"]["id"], int)

version_id = concourse_input["version"]["id"]

output_directory = argv[1]

assert path.exists(output_directory)
assert path.isdir(output_directory)

with open(output_directory + "/state.json", "w") as state_file:
    dump({"id": version_id}, state_file)

print(
    dumps(
        {
            "version": {
                "id": version_id,
            }
        }
    )
)
